from pathlib import Path
from TOKEN import TOKEN


DB_FILE = "tevo.db"
PKL_FILE = "bot_data.pkl"
LOG_FILE = "input.log"
LOG_ACTIVE = True
WINDOW = 1 # Time window in seconds for input rate limiting
LIMIT = 1 # Maximum number of messages allowed per user within the WINDOW

### DO NOT CHANGE PARAMS BELLOW THIS LINE

BASE_DIR = Path(__file__).resolve().parent.parent

BOT_DIR = BASE_DIR / "bot"
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)

DB_PATH = DATA_DIR / DB_FILE
PKL_PATH = DATA_DIR / PKL_FILE
LOG_PATH = DATA_DIR / LOG_FILE

# autogenerated by xdxf_parser.py
SUPPORTED_LANGUAGES = ['be', 'bg', 'br', 'ca', 'cs', 'de', 'el', 'en', 'es', 'fa', 'fr', 'hu', 'it', 'la', 'nl', 'pl', 'pt', 'ro', 'ru', 'sk', 'sv']